
import PyTwitchUtils

#AUTOGENERATED CONFIG FILE

commands = [] #This array will automatically get loaded, so put all the commands you want into here.

def Init(config : PyTwitchUtils.bot.TwitchBotChannelConfig): #Ran when you connect to the channel
    pass
